Models/Prestamo.cs
namespace Proyecto_biblioteca.Models
{
    public class Prestamo
    {
        public int IdPrestamo { get; set; }
        public EstadoPrestamo oEstadoPrestamo { get; set; }
        public Persona oPersona { get; set; }
        public Libro oLibro { get; set; }
        public DateTime FechaDevolucion { get; set; }
        public string TextoFechaDevolucion { get; set; }
        public DateTime FechaConfirmacionDevolucion { get; set; }
        public string TextoFechaConfirmacionDevolucion { get; set; }
        public string EstadoEntregado { get; set; }
        public string EstadoRecibido { get; set; }
        public bool Estado { get; set; }
    }
}

Controllers/BibliotecaController.cs
using Proyecto_biblioteca.Logica;
using Proyecto_biblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;



namespace Proyecto_biblioteca.Controllers
{
    public class BibliotecaController : Controller
    {
        private readonly IConfiguration _configuration;

        public BibliotecaController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        // GET: Biblioteca
        public IActionResult Libros()
        {
            return View();
        }

        public IActionResult Autores()
        {
            return View();
        }

        public IActionResult Editorial()
        {
            return View();
        }

        public IActionResult Categoria()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = CategoriaLogica.Instancia.Listar();
            return Json(new { data = oLista });
        }
        [HttpPost]
        public JsonResult GuardarCategoria(Categoria objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdCategoria == 0) ? CategoriaLogica.Instancia.Registrar(objeto) : CategoriaLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta });
        }

        [HttpPost]
        public JsonResult EliminarCategoria(int IdCategoria)
        {
            bool respuesta = false;
            respuesta = CategoriaLogica.Instancia.Eliminar(IdCategoria);
            return Json(new { resultado = respuesta });
        }



        [HttpGet]
        public IActionResult ListarEditorial()
        {
            List<Editorial> oLista = new List<Editorial>();
            oLista = EditorialLogica.Instancia.Listar();
            return Json(new { data = oLista });
        }
        [HttpPost]
        public JsonResult GuardarEditorial(Editorial objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdEditorial == 0) ? EditorialLogica.Instancia.Registrar(objeto) : EditorialLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta });
        }
        [HttpPost]
        public JsonResult EliminarEditorial(int IdEditorial)
        {
            bool respuesta = false;
            respuesta = EditorialLogica.Instancia.Eliminar(IdEditorial);
            return Json(new { resultado = respuesta });
        }



        [HttpGet]
        public JsonResult ListarAutor()
        {
            List<Autor> oLista = new List<Autor>();
            oLista = AutorLogica.Instancia.Listar();
            return Json(new { data = oLista });
        }
        [HttpPost]
        public JsonResult GuardarAutor(Autor objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdAutor == 0) ? AutorLogica.Instancia.Registrar(objeto) : AutorLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta });
        }
        [HttpPost]
        public JsonResult EliminarAutor(int ididAutor)
        {
            bool respuesta = false;
            respuesta = AutorLogica.Instancia.Eliminar(ididAutor);
            return Json(new { resultado = respuesta });
        }



        [HttpGet]
        public JsonResult ListarLibro()
        {
            List<Libro> oLista = new List<Libro>();

            oLista = LibroLogica.Instancia.Listar();
           
            return Json(new { data = oLista });
        }
        [HttpPost]
public JsonResult GuardarLibro(string objeto, IFormFile imagenArchivo)
{
    Response oresponse = new Response() { resultado = true, mensaje = "" };
    try
    {
        Libro oLibro = JsonConvert.DeserializeObject<Libro>(objeto);

        string GuardarEnRuta = "images/";
        oLibro.RutaPortada = GuardarEnRuta;
        oLibro.NombrePortada = "";
        
        
        if (!Directory.Exists(GuardarEnRuta)){
            Directory.CreateDirectory(GuardarEnRuta); 
        }

        if (oLibro.IdLibro == 0)
        {
            int id = LibroLogica.Instancia.Registrar(oLibro);
            oLibro.IdLibro = id;
            oresponse.resultado = oLibro.IdLibro == 0 ? false : true;
        }
        else
        {
            oresponse.resultado = LibroLogica.Instancia.Modificar(oLibro);
        }

        if (imagenArchivo != null && oLibro.IdLibro != 0)
        {
            string extension = Path.GetExtension(imagenArchivo.FileName);
            GuardarEnRuta = Path.Combine(GuardarEnRuta, oLibro.IdLibro.ToString() + extension);
            oLibro.NombrePortada = oLibro.IdLibro.ToString() + extension;

            using (var stream = new FileStream(GuardarEnRuta, FileMode.Create))
            {
                imagenArchivo.CopyTo(stream);
            }

            oresponse.resultado = LibroLogica.Instancia.ActualizarRutaImagen(oLibro);
        }


    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        oresponse.resultado = false;
        oresponse.mensaje = e.Message;
    }
    return Json(oresponse);
}


        [HttpPost]
        public JsonResult EliminarLibro(int IdLibro)
        {
            bool respuesta = false;
            respuesta = LibroLogica.Instancia.Eliminar(IdLibro);
            return Json(new { resultado = respuesta });
        }


        [HttpGet]
        public JsonResult ListarTipoPersona()
        {
            List<TipoPersona> oLista = new List<TipoPersona>();
            oLista = TipoPersonaLogica.Instancia.Listar();
            return Json(new { data = oLista });
        }


        [HttpGet]
        public JsonResult ListarPersona()
        {
            List<Persona> oLista = new List<Persona>();

            oLista = PersonaLogica.Instancia.Listar();

            return Json(new { data = oLista });
        }
        [HttpPost]
        public JsonResult GuardarPersona(Persona objeto)
        {
            bool respuesta = false;
            objeto.Codigo = GenerarClaveAleatoria();
            respuesta = (objeto.IdPersona == 0) ? PersonaLogica.Instancia.Registrar(objeto) : PersonaLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta });
        }
        [HttpPost]
        public JsonResult EliminarPersona(int IdPersona)
        {
            bool respuesta = false;
            respuesta = PersonaLogica.Instancia.Eliminar(IdPersona);
            return Json(new { resultado = respuesta });
        }

        public string GenerarClaveAleatoria()
    {
           return $"UPIC{Guid.NewGuid().ToString().Substring(0, 8)}";
    }


    }
    public class Response
    {

        public bool resultado { get; set; }
        public string mensaje { get; set; }
    }
    
}

Controllers/PrestamoController.cs
using Proyecto_biblioteca.Logica;
using Proyecto_biblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;


namespace Proyecto_biblioteca.Controllers
{
    public class PrestamoController : Controller
    {
        // GET: Prestamo
        public ActionResult Registrar()
        {
            return View();
        }

        public ActionResult Consultar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GuardarPrestamos(Prestamo objeto)
        {
            bool _respuesta = false;
            string _mensaje = string.Empty;

            _respuesta = PrestamoLogica.Instancia.Existe(objeto);

            if (_respuesta)
            {
                _respuesta = false;
                _mensaje = "El lector ya tiene un prestamo pendiente con el mismo libro";
            }
            else {
                _respuesta = PrestamoLogica.Instancia.Registrar(objeto);
                _mensaje = _respuesta ? "Registro completo" : "No se pudo registrar";
            }

            
            return Json(new { resultado = _respuesta, mensaje = _mensaje });
        }

        [HttpGet]
        public JsonResult ListarEstados()
        {
            List<EstadoPrestamo> oLista = new List<EstadoPrestamo>();
            oLista = PrestamoLogica.Instancia.ListarEstados();
            return Json(new { data = oLista });
        }

        [HttpGet]
        public JsonResult Listar(int idestadoprestamo, int idpersona)
        {
            List<Prestamo> oLista = new List<Prestamo>();
            oLista = PrestamoLogica.Instancia.Listar(idestadoprestamo, idpersona);
            return Json(new { data = oLista });
        }

        [HttpPost]
        public JsonResult Devolver(string estadorecibido,int idprestamo)
        {
            bool respuesta = false;
            respuesta = PrestamoLogica.Instancia.Devolver(estadorecibido,idprestamo);
            return Json(new { resultado = respuesta });
        }
    }
}

Views/Prestamo/Consultar.cshtml
@{
    ViewBag.Title = "Consultar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var usuarioId = Context.Request.Cookies["Usuario"];
}


@if(int.TryParse(usuarioId, out int exist)){
<div class="card shadow mb-4">

    <div class="card-body">
        <div class="form-row align-items-end">
            <div class="col-3">
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Estado Prestamo:</label>
                    <select class="form-control" id="cboestadoprestamo"></select>
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Lectores:</label>
                    <select class="form-control" id="cbolectores"></select>
                </div>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <button id="btnbuscar" class="btn btn-primary btn-block">Buscar</button>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="card shadow">

    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">

                <div class="table-responsive">
                    <table class="table table-bordered" id="tabla" style="width:100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Estado Prestamo</th>
                                <th>Codigo Lector</th>
                                <th>Nombre Lector</th>
                                <th>Titulo Libro</th>
                                <th>Fecha Devolucion</th>
                                <th>Fecha Devolucion Confirmado</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Estado Prestamo</th>
                                <th>Codigo Lector</th>
                                <th>Nombre Lector</th>
                                <th>Titulo Libro</th>
                                <th>Fecha Devolucion</th>
                                <th>Fecha Devolucion Confirmado</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
}else{
     Context.Response.Redirect("/");
}

<!-- Modal -->
<div class="modal fade" id="devolvermodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title">Devolucion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Estado del libro entregado:</label>
                    <textarea class="form-control" id="txtestadolibro" disabled="disabled"></textarea>
                </div>
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Estado del libro recibido:</label>
                    <textarea class="form-control" id="txtestadolibrorecibido"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Volver</button>
                <button type="button" class="btn btn-primary" id="btnGuardar">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="detallemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title">Detalle Devolucion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Estado del libro entregado:</label>
                    <textarea class="form-control" id="txtviewestadolibroentregado" disabled="disabled"></textarea>
                </div>
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Estado del libro recibido:</label>
                    <textarea class="form-control" id="txtviewestadolibrorecibido" disabled></textarea>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        var tabladata;

        $(document).ready(function () {

            jQuery.ajax({
                url: '@Url.Action("ListarPersona", "Biblioteca")',
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.data != null) {
                        $("<option>").attr({ "value": "0"}).text("-- Seleccionar Todos --").appendTo("#cbolectores");
                        $.each(data.data, function (index, value) {

                            if (value.oTipoPersona.idTipoPersona == 3) {
                                $("<option>").attr({ "value": value.idPersona }).text(value.codigo).appendTo("#cbolectores");
                            }
                        });
                    }
                },
                error: function (error) {
                    console.log(error)
                }
            });

            jQuery.ajax({
                url: '@Url.Action("ListarEstados", "Prestamo")',
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                        console.log(data)
                    if (data.data != null) {
                        $("<option>").attr({ "value": "0" }).text("-- Seleccionar Todos --").appendTo("#cboestadoprestamo");
                        $.each(data.data, function (index, value) {
                            $("<option>").attr({ "value": value.idEstadoPrestamo }).text(value.descripcion).appendTo("#cboestadoprestamo");
                        });
                    }
                },
                error: function (error) {
                    console.log(error)
                }
            });


            tabladata = $('#tabla').DataTable({
                responsive:true,
                "ajax": {
                    "url": '@Url.Action("Listar", "Prestamo")' + "?idestadoprestamo=-1&idpersona=-1",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    {
                        "data": "oEstadoPrestamo", render: function (data) {
                            if (data.idEstadoPrestamo != 1) {
                                return '<span class="badge badge-success p-2">' + data.descripcion + '</span>'
                            } else {
                                return '<span class="badge badge-danger p-2">' + data.descripcion + '</span>'
                            }
                        },
                        "width": "120px"
                    },
                    {
                        "data": "oPersona", render: function (data) {
                            return data.codigo
                        }
                    },
                    {
                        "data": "oPersona", render: function (data) {
                            return data.nombre + " " + data.apellido
                        }
                    },
                    {
                        "data": "oLibro", render: function (data) {
                            return data.titulo
                        }
                    },
                    { "data": "textoFechaDevolucion" },
                    { "data": "textoFechaConfirmacionDevolucion" },
                    {
                        "data": "IdPrestamo", "render": function (data, type, row, meta) {
                            if (row.oEstadoPrestamo.idEstadoPrestamo != 1) {
                                return $("<button>").addClass("btn btn-info btn-detalle btn-sm").append(
                                    $("<i>").addClass("far fa-eye")
                                ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML
                            } else {
                                return $("<button>").addClass("btn btn-primary btn-devolver btn-sm").append(
                                    $("<i>").addClass("fas fa-undo-alt")
                                ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML
                            }


                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "90px"
                    }

                ]
            });
        })

        $("#btnbuscar").on("click", function () {
            tabladata.ajax.url('@Url.Action("Listar", "Prestamo")' + "?idestadoprestamo=" + $("#cboestadoprestamo").val() + "&idpersona=" + $("#cbolectores").val()).load();
        })


        $(document).on('click', '.btn-devolver', function (event) {
            var json = $(this).data("informacion")

            $("#txtestadolibro").val(json.estadoEntregado);
            $("#btnGuardar").data("idprestamo", json.idPrestamo);

            $("#devolvermodal").modal("show");


        });

        $(document).on('click', '.btn-detalle', function (event) {
            var json = $(this).data("informacion")

            $("#txtviewestadolibroentregado").val(json.estadoEntregado);
            $("#txtviewestadolibrorecibido").val(json.estadoRecibido);

            $("#detallemodal").modal("show");
        });

        $("#btnGuardar").on("click", function () {
            var _idprestamo = $(this).data("idprestamo");

            jQuery.ajax({
                url: '@Url.Action("Devolver", "Prestamo")',
                type: "POST",
                data: {estadorecibido: $("#txtestadolibrorecibido").val() , idprestamo : _idprestamo },
                success: function (data) {
                    if (data.resultado) {
                        tabladata.ajax.reload();
                        alert("Se registro la devolución");
                        $("#devolvermodal").modal("hide");
                    } else {
                        alert("No se pudo registro la devolución");
                        $("#devolvermodal").modal("hide");
                    }
                },
                error: function (error) {
                    console.log(error)
                }
            });
        })




    </script>
}